export HomeContainer from './Home/HomeContainer'
export MainContainer from './Main/MainContainer'
export AuthenticateContainer from './Authenticate/AuthenticateContainer'
export ResultsContainer from './Results/ResultsContainer'
export ModalContainer from './Modal/ModalContainer'
export DecideContainer from './Decide/DecideContainer'
export LogoutContainer from './Logout/LogoutContainer'